fake_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - summit_xls_arm_shoulder_pan_joint
    - summit_xls_arm_shoulder_lift_joint
    - summit_xls_arm_elbow_joint
    - summit_xls_arm_wrist_1_joint
    - summit_xls_arm_wrist_2_joint
    - summit_xls_arm_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      summit_xls_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      summit_xls_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      summit_xls_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      summit_xls_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      summit_xls_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      summit_xls_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - summit_xls_arm_shoulder_pan_joint
    - summit_xls_arm_shoulder_lift_joint
    - summit_xls_arm_elbow_joint
    - summit_xls_arm_wrist_1_joint
    - summit_xls_arm_wrist_2_joint
    - summit_xls_arm_wrist_3_joint

