controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - summit_xls_arm_shoulder_pan_joint
      - summit_xls_arm_shoulder_lift_joint
      - summit_xls_arm_elbow_joint
      - summit_xls_arm_wrist_1_joint
      - summit_xls_arm_wrist_2_joint
      - summit_xls_arm_wrist_3_joint
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: up